### ISSUE TITLE
Previous / Next if item count is <= 3

### ISSUE THREAD

**Issue by KarabanDev** [wjuniorgit/loop_page_view#12]
Hi, and ty for ur great job 
Regarding to this answer https://github.com/wjuniorgit/loop_page_view/issues/5 this is intended behavior
But is there any workaround to accomplish correct scroll direction and actions like previos/next page if item count is <= 3 ?  

Best regards!

**Comment by SilkeNL** [comment]
I agree a solution should exist, its odd you would be moving forward if you called previous page

**Comment by wjuniorgit** [comment]
`LoopScrollMode`

Values:
* `shortest`:  `LoopPageController` will animate to the closest page. For example, if the current page is 1 and the target page is 5, but the total number of pages is 6, the `LoopPageController` will go backwards (from 1 to 6 to 5) instead of forwards (from 1 to 2 to 3 to 4 to 5). This is because the shortest path from 1 to 5 in this case is to go backwards.
* `forwards`:  `LoopPageController` will always animate forwards to reach the target page. Even if the target page is technically closer when moving backwards, this option will make the controller move forwards until it reaches the target page.
* `backwards`:  `LoopPageController` will always animate backwards to reach the target page. Similar to `forwards`, but in the opposite direction. Even if the target page is technically closer when moving forwards, this option will make the controller move backwards until it reaches the target page.
