### ISSUE TITLE
nextPage, previousPage, animateToPage direction problem on the last page and on the first page

### ISSUE THREAD

**Issue by mu-projects** [wjuniorgit/loop_page_view#5]
When nextPage runs on the last page, it should go forward to the first page, not go backwards.

**Comment by wjuniorgit** [comment]
Hi, thanks for opening the issue, I will check It out.

**Comment by wjuniorgit** [comment]
Hi @wfinf could you elaborate a little more on your use case that triggers this issue?
I tested with the Example code and it seems to be working as expected

https://user-images.githubusercontent.com/3476417/136302343-8277d924-65e8-456b-aeba-fa4c359857a5.mp4

**Comment by mu-projects** [comment]
It works incorrectly when itemCount = 2

**Comment by wjuniorgit** [comment]
Thanks, I will take a look at it.

**Comment by wjuniorgit** [comment]
Hi @wfinf, sorry for the delayed response. 
What you described is actually the expected behavior! 
The widgets inside `LoopPageView` are as in a 'closed loop'. You can manually move the loop to any direction you want, but when animating the move, `LoopPageController` will always move in the direction with "less steps". 
When the travel distance is equal for both directions `LoopPageController` will always prefer to stay in the 'current loop' and will move to the left. 
This is what happens when itemCount is 2 and you want to animate the move from page 1 to page 0.
